export const metadata = {
  title: {
    absolute: "",
    default: "Nextjs Lecture With Yoni",
    template: "%s | NextNext",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ background: "lightblue", padding: "1rem" }}>
          this is the header
        </header>
        {children}
        <footer style={{ background: "ghostwhite", padding: "1rem" }}>
          this is the footer
        </footer>
      </body>
    </html>
  );
}
